name: Run Twitter Sentiment Naive Bayes

on:
  push:
    branches:
      - main

jobs:
  run-nb-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pandas scikit-learn matplotlib seaborn

      - name: Run Naive Bayes script
        run: python NB-TWITTER.py

      - name: Upload confusion matrix plot
        uses: actions/upload-artifact@v4
        with:
          name: confusion-matrix
          path: confusion_matrix.png
"""

# Simpan sebagai file YAML
yaml_path = "/mnt/data/run-twitter-nb.yml"
with open(yaml_path, "w") as f:
    f.write(yaml_content)

yaml_path
